# You can edit this file to add GitHub Sponsors, Ko-fi, Patreon, or other funding platforms.
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-repository-files#about-files-in-the-github-sponsors-tab
